/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.ufrsciencestech.panier;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author jg625300
 */
public class VueGraphique extends JFrame implements Vue, Observer {

    // Classe observatrice d'une autre classe observée
    // Appel de la méthode update au changement de la classe observée
    
    private JButton inc, dec;
    private JLabel affiche;
    /**
     * Creates new form VueGraphique
     */
    public VueGraphique() 
    {
        inc = new JButton("+");
        dec = new JButton("-");
        affiche = new JLabel("0", JLabel.CENTER);
        this.add(inc, BorderLayout.NORTH);
        this.add(dec, BorderLayout.SOUTH);
        this.add(affiche, BorderLayout.CENTER);
    }
    
    public void update(Observable m, Object o)
    {
        Panier p = (Panier) o;
        affiche.setText(Integer.toString(p.getSize()));
    }
    
    public void addControleur(Controleur c) 
    {
        inc.addActionListener(c);
        dec.addActionListener(c);
    }
    
    public int getValeur(ActionEvent e)
    {
        JButton b = (JButton) e.getSource();
        if(b != inc && b != dec) 
            return 0;  //autre evenement que l'appui sur l'un des 2 boutons
        return (b==inc) ? 1 : -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
